import type { Invitation } from './types'

export function getDemoInvitation(templateId: string): Invitation {
  return {
    id: `demo-${templateId}`,
    user_id: 'demo',
    slug: `demo-${templateId}`,
    template_id: templateId,
    groom_name: 'Rizky',
    bride_name: 'Amara',
    groom_full_name: 'Muhammad Rizky Pratama',
    groom_father: 'Bapak Hendra Pratama',
    groom_mother: 'Ibu Sari Dewi',
    groom_instagram: 'rizky.pratama',
    bride_full_name: 'Amara Putri Salsabila',
    bride_father: 'Bapak Ahmad Fauzi',
    bride_mother: 'Ibu Nurul Hidayah',
    bride_instagram: 'amara.salsabila',
    event_date: new Date(Date.now() + 60 * 24 * 60 * 60 * 1000).toISOString(),
    location_name: 'Ballroom Grand Sahid Jaya, Jakarta',
    location_maps_url: 'https://maps.google.com',
    akad_date: new Date(Date.now() + 60 * 24 * 60 * 60 * 1000 - 3 * 60 * 60 * 1000).toISOString(),
    akad_location: 'Masjid Al-Ikhlas, Jakarta Selatan',
    akad_maps_url: 'https://maps.google.com',
    music_url: null,
    cover_photo_url: null,
    couple_photo_url: null,
    groom_photo_url: null,
    bride_photo_url: null,
    opening_text: 'Bismillahirrahmanirrahim\n\nDengan memohon rahmat dan ridho Allah SWT, kami mengundang Bapak/Ibu/Saudara/i untuk hadir dan memberikan doa restu pada pernikahan kami.',
    quran_verse: 'Dan di antara tanda-tanda kekuasaan-Nya ialah Dia menciptakan untukmu pasangan hidup dari jenismu sendiri supaya kamu mendapat ketenangan hati.',
    quran_surah: 'QS. Ar-Rum: 21',
    dresscode_color: '#C9A84C',
    dresscode_note: 'Kami berharap tamu undangan berkenan mengenakan warna-warna elegan pada hari istimewa kami.',
    love_story: 'Pertama Bertemu|Januari 2021|Kami pertama kali bertemu di sebuah acara seminar di Jakarta. Sebuah pertemuan sederhana yang ternyata menjadi awal dari segalanya.\nMulai Dekat|Juni 2021|Dari teman biasa, kami mulai sering berbagi cerita dan tawa. Tanpa disadari, hati kami semakin dekat satu sama lain.\nResmi Bersama|Desember 2021|Di bawah langit Jakarta yang cerah, Rizky mengungkapkan perasaannya. Dan Amara menjawab dengan senyuman yang tak terlupakan.\nLamaran|Maret 2024|Dengan penuh cinta dan doa, Rizky melamar Amara di hadapan kedua keluarga. Sebuah momen yang mengharukan dan penuh kebahagiaan.',
    video_url: null,
    live_streaming_url: null,
    cover_type: 'gradient',
    silhouette_variant: 'standing',
    photo_frame: 'oval',
    dresscode_enabled: true,
    photo_mode: 'single',
    is_published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    digital_gifts: [
      {
        id: 'demo-gift-1',
        invitation_id: `demo-${templateId}`,
        bank_name: 'BCA',
        account_number: '1234567890',
        account_holder: 'Muhammad Rizky Pratama',
        qris_url: null,
      },
      {
        id: 'demo-gift-2',
        invitation_id: `demo-${templateId}`,
        bank_name: 'Mandiri',
        account_number: '0987654321',
        account_holder: 'Amara Putri Salsabila',
        qris_url: null,
      },
    ],
    guestbook: [
      {
        id: 'demo-gb-1',
        invitation_id: `demo-${templateId}`,
        guest_name: 'Budi Santoso',
        message: 'Selamat menempuh hidup baru! Semoga menjadi keluarga yang sakinah, mawaddah, warahmah. 🤍',
        attendance_status: 'hadir',
        created_at: new Date().toISOString(),
      },
      {
        id: 'demo-gb-2',
        invitation_id: `demo-${templateId}`,
        guest_name: 'Siti Rahayu',
        message: 'Barakallahu lakuma wa baraka alaikuma wa jama\'a bainakuma fi khair. Aamiin.',
        attendance_status: 'hadir',
        created_at: new Date().toISOString(),
      },
    ],
    gallery: [],
  }
}
